delete {?uid rdf:type mig:martcolumn . ?uid ?p ?o }
where { ?uid rdf:type mig:martcolumn . ?uid ?p ?o };
delete {?uid mig:parentVisualId1 ?b}
where {?uid mig:parentVisualId1 ?b};
##
insert {
  ?uid rdf:type mig:martcolumn .
  ?uid mig:hasSqlName ?colName .
  ?uid mig:dataType ?dataType .
  ?uid mig:hasOrder ?colOrder .
  ?uid mig:hasQueryRelation ?qrel .   
  ?uid mig:hasQueryColumn ?qcol .
  ?uid mig:hasExportQuery ?exp_query .
  ?uid mig:hasMart ?mart .
  ?uid mig:hasMsDashTable ?tab_rel .
  ?uid mig:hasVisualLabel ?hasVisualLabel .
  ?tableTo mig:hasVisualLabel ?hasVisualLabelTableTo .
  #?uid mig:parentVisualId1 ?exp_query .
  ?exp_query mig:parentVisualId1 ?mart .
  ?tableTo mig:parentVisualId1  ?exp_query .
  ?col  mig:parentVisualId1  ?tableTo .  
  ?uid  mig:parentVisualId1  ?col .  
  ?tableTo mig:hasPrefix ?TableToPrefix .
  ?tableTo mig:hasExportSqlName ?hasExportSqlName .
  ?col mig:hasExportSqlName ?colName .
} 
#
where {
select 

  ?tab_rel ?qrel ?qcol ?tabtojsname ?tabtosqlname ?rel_order (concat('t',str(?rel_order))  as ?prefix)
  (IF(coalesce(?coltype,'')="calculated",concat('calc_t',str(?rel_order),'_',str(?colOrder)),
      concat('t',str(?rel_order),'_',str(?colOrder),'_',?sqlName)
    ) as ?colName) ?coljsname ?colOrder ?coltype ?dataType
  (iri(concat('http://www.example.com/MIGRATION#',struuid())) as ?uid) 
      ?exp_query ?mart 
  (concat(?colName,'\n',?coljsname,'\n',?dataType) as ?hasVisualLabel)
  ?col ?tab_rel ?tableTo 
  (concat(?tabtojsname,'\n',?tabtosqlname ,'\n','export_pbi.m',str(?mart_order),'_t_',str(?rel_order),?hasSQLTableName ) as  ?hasVisualLabelTableTo)
  (concat('m',str(?mart_order),'_t_',str(?rel_order),?hasSQLTableName ) as  ?TableToPrefix)
  (concat('export_pbi.m',str(?mart_order),'_t_',str(?rel_order),?hasSQLTableName ) as  ?hasExportSqlName)
  
  WHERE {
    { 
      ?exp_query rdf:type mig:dashexportquery .
      ?exp_query mig:hasMart ?mart .
      ?mart mig:hasOrder ?mart_order .
      ?exp_query mig:hasMsDashTable ?tableTo.      
      ?tableTo mig:hasSqlName ?tabtosqlname .
      ?tableTo js:name ?tabtojsname .
      optional{?tableTo mig:hasSQLTableName ?hasSQLTableName }.
    
      ?mart rdf:type mig:dashmart .
      #bind(mig:Nf76bc87394d14b3abe1a6475af28a214 as ?exp_query)
      ?exp_query rdf:type mig:dashexportquery .
      ?qrel mig:hasExportQuery ?exp_query .
      ?qrel rdf:type mig:queryrelation .
      ?qrel mig:hasOrder ?rel_order . 
      optional{?qrel mig:parentFromRelation	?parentRelFrom }     .

      filter(coalesce(?parentRelFrom,'')='' ) .
          ?qcol mig:hasQueryRelation ?qrel .  
          ?qcol rdf:type mig:queryrelationcolumn .  
          ?qcol mig:hasColumn ?col .
          ?qcol mig:hasOrder ?colOrder .
          ?col mig:hasSqlName ?sqlName .
          ?col js:name ?coljsname .  
          optional {?col js:type ?coltype}
          ?col js:dataType ?dataType .
          
    } 
    UNION 
        {
          ?exp_query rdf:type mig:dashexportquery .
          ?exp_query mig:hasMart ?mart .
          ?mart rdf:type mig:dashmart .
          ?mart mig:hasOrder ?mart_order .
          ?exp_query rdf:type mig:dashexportquery .
          ?qrel mig:hasExportQuery ?exp_query .
          ?qrel rdf:type mig:queryrelation .
          ?qrel mig:hasOrder ?rel_order .
          ?qrel mig:parentRelation ?tab_rel .
          ?tableTo  mig:hasRelationshipTo  ?tab_rel.
          ?tableTo mig:hasSqlName ?tabtosqlname .
          ?tableTo js:name ?tabtojsname .
          optional{?tableTo mig:hasSQLTableName ?hasSQLTableName }.
          ?qcol mig:hasQueryRelation ?qrel .  
          ?qcol rdf:type mig:queryrelationcolumn .  
          ?qcol mig:hasColumn ?col .
          ?qcol mig:hasOrder ?colOrder .
          ?col mig:hasSqlName ?sqlName .
          ?col js:name ?coljsname .  
          optional {?col js:type ?coltype}
          ?col js:dataType ?dataType .
        }
    }    
  order by ?mart ?exp_query xsd:integer(?rel_order) xsd:integer(?colOrder)     
};
